title: MMWC - Milwaukee Muslim Women's Coalition
email: azizj.consulting@gmail.com
description: >
  Milwaukee Muslim Women's Coalition is a trusted resource on Islam, Muslim Women and Islamic issues in the
  Greater Milwaukee area and beyond.
keywords: >
  MMWC, Milwaukee Muslim Women's Coalition, Muslim Women, Women in Islam, Wisconsin Muslims,
  Milwaukee Muslims, United States Muslims, Islam in the United States, Interfaith, Community, muslim, islam, women,
  nonprofit, islamaphobia, islamic answers
author: Aziz Javed
url: "http://mmwconline.org" # the base hostname & protocol for your site

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - _src

gems: [jekyll-paginate, jekyll-sitemap]
paginate_path: "/blog/page:num/"
paginate: 4
excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: ""
    values:
      baseurl: "../"
      layout: "default"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "blog"
      baseurl: "../../../"
      assetConfig: "blog"